# Generated by Django 4.0.2 on 2022-02-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=200)),
                ('identifier', models.CharField(choices=[('email', 'Email'), ('phone_number_sms', 'Phone')], max_length=200)),
            ],
        ),
    ]
